### ISSUE TITLE
这个报错是什么原因导致的?

### ISSUE THREAD

**Issue by zonggeng** [liuzhuoling2011/baidupcs-web#10]
列出分享列表: 遇到错误, 远端服务器返回错误, 代码: -6, 消息: 请重新登录

**Comment by SingingDalong** [comment]
me too....

**Comment by liuzhuoling2011** [comment]
我在windows版本下没有遇到这个问题, 你们用的什么系统版本?

**Comment by SingingDalong** [comment]
Windows 7 x86 and Windows Server 2016...Both have the same error.

**Comment by SshazeP** [comment]
win10 x64 企业版

**Comment by lan493** [comment]
我也是这样，想换个号，结果直接不能用了

**Comment by Luluno01** [comment]
同，win10专业版及树莓派3B。要不试一下改成cookie+UA登录？

**Comment by liuzhuoling2011** [comment]
解决了一个websocket在远程机上连接不了的bug, 大概明天会放出更新, 看看到时候能不到解决你们这个问题

**Comment by liuzhuoling2011** [comment]
你们的问题解决了么

**Comment by SshazeP** [comment]
报错 No permission to do this operation
 还是列不出文件列表
那应用id改了的也这样

**Comment by liuzhuoling2011** [comment]
@SshazeP 不科学呀, 你用的最新的版本吗? 还有可以换个电脑试一下

**Comment by liuzhuoling2011** [comment]
这个问题有点久远了, 没有更新的话, 就关闭了把

**Comment by Luluno01** [comment]
@liuzhuoling2011 我在Windows上已经能使用了

**Comment by SshazeP** [comment]
> 这个问题有点久远了，没有更新的话，就关闭了把

好的  我也可以正常使用了  感谢
