### ISSUE TITLE
你好，又来打扰你了。安卓arm64的使用问题。

### ISSUE THREAD

**Issue by user1121114685** [liuzhuoling2011/baidupcs-web#104]
我写了一个magisk模块安卓arm64的，发现寻求dns的时候寻求到了：：1（ipv6的127.0.0.1）,导致无法使用。请问能内置dns进行解析吗？

ps 我已经尝试过53端口劫持，和更换dns服务

**Comment by liuzhuoling2011** [comment]
这个不太明白你的意思

**Comment by user1121114685** [comment]
也许我应该截图。
