### ISSUE TITLE
QQ注册账号的不能登录

### ISSUE THREAD

**Issue by qiuquanm** [liuzhuoling2011/baidupcs-web#107]
可以添加cookie登录功能
![image](https://user-images.githubusercontent.com/28824049/52634737-f3e7b700-2f02-11e9-9d93-91aa30272467.png)

**Comment by liuzhuoling2011** [comment]
目前版本已经支持了bduss登录，详情可见
https://github.com/iikira/BaiduPCS-Go/wiki/%E5%85%B3%E4%BA%8E-%E8%8E%B7%E5%8F%96%E7%99%BE%E5%BA%A6-BDUSS
