### ISSUE TITLE
同时下载量对后添加的任务暂时不起作用

### ISSUE THREAD

**Issue by wwqgtxx** [liuzhuoling2011/baidupcs-web#11]
如题，在设置中如果设置了同时下载量为5，先添加一个下载任务，再在网页界面上添加另一个的时候，那个任务并不会启动而是会等待之前的任务结束之后才会继续，而且该任务也无法删除。
个人分析应该是web的rpc调用和后端的接口还是有诸多分离的地方导致了这个问题，比如其他issue中提到的暂停的问题，下载历史无法保存的问题，建议可以把baidupcs-go当做一个库来调用，自行开发一个server端来控制整体的运行，而不是把该项目当做baidupcs-go的一个附属产品，这样会使很多功能的运转和大家希望的不太一样

**Comment by liuzhuoling2011** [comment]
非常感谢认真的评论
目前确实是把baidupcs-go当做一个库来调用，自行开发一个server端来控制整体的运行, 只不过有些功能需要深入的改进流程才可以做到. 在发布的时候我也发现了同时下载的问题, 本来想提交了pr等原作者iikira批准merge后一起解决这些问题, 毕竟网页端和命令行有些操作行为是不一致的. 但是他一直不批pr, 也很尴尬, 后续不排除我自己深入改进一下

**Comment by wwqgtxx** [comment]
其实这个地方可以用一个比较粗暴的方式解决问题而不需要干涉baidupcs-go库的本身逻辑，即通过popen一个子进程来完成单个的下载任务，实现两个程序的彻底分离，这样如果需要暂停、停止的话也更为容易，直接给子进程一个signal即可，同时还不会因为baidupcs-go本身的命令行逻辑导致server端出现一些行为异常。当然这么做也有个缺陷就是会增加系统的资源开销(比如内存开销，这个没有办法解决；启停子进程造成的开销倒是可以通过进程池来缓解)，不过好处是两个程序的维护会更加方面，作为本项目只需要操作baidupcs-go的cli而不需要关心他的内部工作，也就不需要一直等待原作者merge.
从工作原理上说，我上述方法更贴近与我的视频下载插件的实现
https://github.com/wwqgtxx/wwqLyParse/blob/master/wwqLyParse/parsers/annieparser.py
https://github.com/wwqgtxx/wwqLyParse/blob/master/wwqLyParse/parsers/yougetparser.py
