### ISSUE TITLE
希望加入安卓版

### ISSUE THREAD

**Issue by pxw139** [liuzhuoling2011/baidupcs-web#110]
安卓终端用Linux版会遇到网络问题，emmmmm

**Comment by liuzhuoling2011** [comment]
这个可以考虑， 有时间做一下

**Comment by thanksshu** [comment]
附议，模仿BaiduPCS-Go，在Termux下进行测试确实不能使用。

**Comment by Super-Users** [comment]
termux下可以用的，我昨天用了，不限速，termux模拟linux系统，可以完全使用linux命令进行各种操作，昨天配置后成功下载，速度比Windows快的太多了
![Screenshot_2019-05-15-09-33-49-97](https://user-images.githubusercontent.com/50556556/57763070-45d2ef80-7733-11e9-9022-8a10872b71aa.png)

**Comment by Super-Users** [comment]
> 附议，模仿BaiduPCS去，在Termux下进行测试确实不能使用。

可以用的，而且速度很快，看我下面的图兄弟

**Comment by thanksshu** [comment]
> > 附议，模仿BaiduPCS去，在Termux下进行测试确实不能使用。
> 
> 可以用的，而且速度很快，看我下面的图兄弟

@Super-Users 请问是如何完成的？有如下错误未解决：
![IMG_20190515_115427](https://user-images.githubusercontent.com/30020001/57767571-f4623a80-7709-11e9-99c6-b94f6dae7967.jpg)

**Comment by sukanka** [comment]
> > > 附议，模仿BaiduPCS去，在Termux下进行测试确实不能使用。
> > 
> > 
> > 可以用的，而且速度很快，看我下面的图兄弟
> 
> @Super-Users 请问是如何完成的？有如下错误未解决：
> ![IMG_20190515_115427](https://user-images.githubusercontent.com/30020001/57767571-f4623a80-7709-11e9-99c6-b94f6dae7967.jpg)

附议，我的也是这个错误，不能登录帐号

**Comment by liuzhuoling2011** [comment]
新版的已经加上对安卓的支持
