### ISSUE TITLE
【安全漏洞】已登录用户的bduss信息泄漏

### ISSUE THREAD

**Issue by yuxiaokui** [liuzhuoling2011/baidupcs-web#115]
访问这个链接：api/v1/user?method=get
会泄漏已登录的用户bduss 
及时lock了，也会获取到。

造成的后果大家都懂。

**Comment by user1121114685** [comment]
试试加入密码？

**Comment by yuxiaokui** [comment]
我上面说了，即使lock了，也会获取到bduss     
比如在zoomeye上随便找到的一个  http://113.120.112.241:9999/#/lock
界面是锁住的。
但是访问 http://113.120.112.241:9999/api/v1/user?method=get
会泄漏bduss

**Comment by user1121114685** [comment]
大哥你也不要把你服务器ip给漏出来撒。。。。

**Comment by user1121114685** [comment]
你这样你的账号岂不是直接漏了。。。

**Comment by loliconer** [comment]
嗯，这确实是个大bug，需要赶紧处理！ @liuzhuoling2011

**Comment by liuzhuoling2011** [comment]
这个确实是。。。我尽快修复

**Comment by liuzhuoling2011** [comment]
新版本已经修复
