### ISSUE TITLE
能否限制只监听localhost和127.0.0.1

### ISSUE THREAD

**Issue by goxofy** [liuzhuoling2011/baidupcs-web#116]

**Comment by liuzhuoling2011** [comment]
不太清楚你的意思

**Comment by goxofy** [comment]
就是只能本机访问，加参数监听0.0.0.0之后才能提供局域网访问

**Comment by liuzhuoling2011** [comment]
我感觉这个问题算是比较小众的了
建议可以在你服务器防火墙端新建一个规则，屏蔽掉其他IP对你特定端口的访问

**Comment by goxofy** [comment]
现阶段，全网段监听有很严重的安全问题啊，大多数web服务类的应用程序至少默认都应该是只监听本地

**Comment by liuzhuoling2011** [comment]
好的， 采纳你的建议，新增只监听本地的模式，在新版本发布

**Comment by Explorer1092** [comment]
> 好的， 采纳你的建议，新增只监听本地的模式，在新版本发布

只监听本地,导致无法docker化。建议增加参数，允许远程访问

**Comment by goxofy** [comment]
@Explorer1092 文档内有参数说明
