### ISSUE TITLE
做反代之后Https访问无法下载

### ISSUE THREAD

**Issue by IMLR** [liuzhuoling2011/baidupcs-web#122]
安装在群晖NAS上，域名http模式访问，移动端和PC端都可以正常添加下载任务，做了反代之后Https模式下访问不能正常添加下载任务，PC端提示添加任务成功但下载列表中没有，移动端点击下载无反应。

**Comment by liuzhuoling2011** [comment]
这个实话说我不太清楚。。。

**Comment by norlight** [comment]
好像遇到了同样的问题。症状除了和楼主的一样外，退出登录后，输入用户名时，提示“WebSocket连接发生错误”。所以猜测可能内部其他数据传递也是用的ws，反代没能把ws转发过去。

**Comment by osdu** [comment]
```

#
# Default server configuration
#

upstream baidupcs {
	server 127.0.0.1:5299;
}


server {
	listen ....;
	listen .... ssl;

	server_name ...;

	location / {
		proxy_pass http://baidupcs;
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	}

	location /ws {
		proxy_pass http://baidupcs;
		proxy_http_version 1.1;
		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Connection "upgrade";

		proxy_connect_timeout 5s;
		proxy_read_timeout 30m;
		proxy_send_timeout 10s;
	}
}
```

**Comment by MutingLeng** [comment]
> ```
> 
> #
> # Default server configuration
> #
> 
> upstream baidupcs {
> 	server 127.0.0.1:5299;
> }
> 
> 
> server {
> 	listen ....;
> 	listen .... ssl;
> 
> 	server_name ...;
> 
> 	location / {
> 		proxy_pass http://baidupcs;
> 		proxy_set_header Host $host;
> 		proxy_set_header X-Real-IP $remote_addr;
> 		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
> 	}
> 
> 	location /ws {
> 		proxy_pass http://baidupcs;
> 		proxy_http_version 1.1;
> 		proxy_set_header Upgrade $http_upgrade;
> 		proxy_set_header Connection "upgrade";
> 
> 		proxy_connect_timeout 5s;
> 		proxy_read_timeout 30m;
> 		proxy_send_timeout 10s;
> 	}
> }
> ```

多谢，亲测可用。

**Comment by shunjiankongbai** [comment]
我的也是同样的问题，估计是不支持https，我改成http就可以外网连接下载了，但是速度问题还是没法，SVIP都没用···

**Comment by shunjiankongbai** [comment]
哪位能帮帮我，我用的apache2.49+ubunt userver 18.04.3，不知道如何配置wss，只搞定了页面https

**Comment by creepsnail** [comment]
控制面板 => 应用程序门户 => 反向代理 => 编辑刚才添加的条目 => 自定义标题 => 点小箭头 => WebSocket

**Comment by happysoul** [comment]
难道只有我用caddy反向代理这个。。。
`我的二级域名:80 {
    tls off
    proxy / 127.0.0.1:5299/ {
        websocket
        transparent
    }
}`
通过域名访问，可以打通ws，不过选了文件点下载只能看到一次下载中的文件，刷新页面再去看下载任务就是空白了，chrome控制台和网络都没有报错。。。
