### ISSUE TITLE
上传队列问题

### ISSUE THREAD

**Issue by 786259135** [liuzhuoling2011/baidupcs-web#123]
添加上传队列后切换账号，再切换回之前添加上传队列的账号，此时去看上传列表是空的（不显示）

后台程序显示文件正在上传（有进度）

**Comment by liu-xun** [comment]
遇到了类似的问题，添加上传队列后关闭浏览器再重新打开不会显示上传队列（终端内有显示上传任务）

**Comment by 786259135** [comment]
https://github.com/liuzhuoling2011/baidupcs-web/issues/21

似乎跟这个情况类似

**Comment by liuzhuoling2011** [comment]
同样的问题，暂时还没精力解决 #21

**Comment by bsharkl** [comment]
![image](https://user-images.githubusercontent.com/17378745/54575977-50258580-4a31-11e9-87cd-25b911d12aa1.png)
 WebSocket连接发生错误 [object Event]

**Comment by liuzhuoling2011** [comment]
> ![image](https://user-images.githubusercontent.com/17378745/54575977-50258580-4a31-11e9-87cd-25b911d12aa1.png)
> WebSocket连接发生错误 [object Event]

你好， 什么情况下会发生呢？可以详细描述一下么？顺便也截图一下后台输出吧， 非常感谢

**Comment by bsharkl** [comment]
群辉docker上运行了，根据提示进行了升级，替换指定目录的BaiduPCS-Go文件，重新启动docker后进入页面，还要键盘一输入内容就连续跳出此条目。

**Comment by flynohigher** [comment]
> > ![image](https://user-images.githubusercontent.com/17378745/54575977-50258580-4a31-11e9-87cd-25b911d12aa1.png)
> > WebSocket连接发生错误 [object Event]
> 
> 你好， 什么情况下会发生呢？可以详细描述一下么？顺便也截图一下后台输出吧， 非常感谢

通过“域名-群晖反向代理-本地IP+端口”访问时，在登陆页面用户名输入框，每输入一个字母就生成一条“Web Socket连接发生错误”。如果直接在本地用IP+端口访问则没有这个问题。
