### ISSUE TITLE
下载管理记录不能显示

### ISSUE THREAD

**Issue by awerdx520** [liuzhuoling2011/baidupcs-web#129]
#### 环境：
 `OS:` Deepin 15.9.2 x86_64 
 `Kernel: `4.15.0-29deepin-generic 
`  go version` go1.11 linux/amd64
`baidupcs-web-3.6.5`
`google-chrome: `版本 73.0.3683.75（正式版本） （64 位）
#### Issue：
web中在下载，然后关闭网页重新访问，下载不显示，也没有下载记录了。
![1](https://user-images.githubusercontent.com/15448027/54474859-357ec100-4825-11e9-9567-d4b3ae1fcabf.png)

**Comment by liuzhuoling2011** [comment]
同样的问题，暂时还没精力解决 #21

**Comment by 17huiwei** [comment]
我也遇到这个问题，不知如何解决，如果能直接管理上传下载就很完美了。
