### ISSUE TITLE
这个界面远程无法使用

### ISSUE THREAD

**Issue by HiyungXu** [liuzhuoling2011/baidupcs-web#13]
我在家中的群晖NAS上安装了你的程序，远程访问能出现登录界面，但是无法登录，本机使用windows版是可以的。

**Comment by iiiiiii1** [comment]
Linux也是，无法登陆

**Comment by liuzhuoling2011** [comment]
解决了一个websocket在远程机上连接不了的bug, 大概明天会放出更新
