### ISSUE TITLE
错误代码: -1, 消息: 网络请求失败, Post https://wappass.baidu.com/wp/api/login: read tcp 10.50.160.38:61175->180.97.104.218:443: wsarecv: An existing connection was forcibly closed by the remote host.

### ISSUE THREAD

**Issue by zhezhe168** [liuzhuoling2011/baidupcs-web#132]
错误代码: -1, 消息: 网络请求失败, Post https://wappass.baidu.com/wp/api/login: read tcp 10.50.160.38:61175->180.97.104.218:443: wsarecv: An existing connection was forcibly closed by the remote host.

**Comment by liuzhuoling2011** [comment]
估计是百度抽风了一下

**Comment by zhezhe168** [comment]
不行，今天在输入验证码按登录后又没反应了，bduss登录也没反应，但是速盘那些倒是正常登录，不知道是什么问题
