### ISSUE TITLE
3.6.5CPU占用高

### ISSUE THREAD

**Issue by w3334532** [liuzhuoling2011/baidupcs-web#134]
更新到3.6.5以后好像CPU占用很高,top命令查看占用了30%多,

**Comment by chenxiccc** [comment]
I've got the same problem.
CPU range from 6% to 20%.

**Comment by RouRouX** [comment]
遇到同样的问题，旧版没这情况

**Comment by burning** [comment]
同样 非常耗CPU

**Comment by miniers** [comment]
机器都发烫了😂 3.6.4没问题

**Comment by gkl1368** [comment]
同样问题 到3.6.6也木有解决

**Comment by alisonY** [comment]
+1 
3.6.6 CPU占用也很高

**Comment by liuzhuoling2011** [comment]
![image](https://user-images.githubusercontent.com/8407297/56032159-fc6a3b80-5d53-11e9-9e1d-3be66cf167e8.png)
应该找到问题了， 看看怎么解决

**Comment by liuzhuoling2011** [comment]
3.6.7 已经fix
