### ISSUE TITLE
 错误代码: 50028, 消息: 系统繁忙，请稍候再试(50028)

### ISSUE THREAD

**Issue by Hunglish92** [liuzhuoling2011/baidupcs-web#135]
错误代码: 50028, 消息: 系统繁忙，请稍候再试(50028)

**Comment by shawn0915** [comment]
same problem.
latest release version on centos 7.

**Comment by Jianfan-Wu** [comment]
同样出现这个问题，登录不上版本windows .3.6.6

**Comment by Xfireman** [comment]
我刚才也遇到了这个问题，测试了一下，发现是我密码错误多次被锁了。
建议可以尝试一下用账号密码直接登录百度云，看看是不是被锁了。
如果被锁了找回一下密码就行了。

**Comment by shawn0915** [comment]
这样啊？可是我的客户端一直在线啊，我再试试好了，谢谢您。



Regards,
ShawnYan
 
发件人： XFireMan
发送时间： 2019-04-09 14:04
收件人： liuzhuoling2011/baidupcs-web
抄送： Shawn Yan; Comment
主题： Re: [liuzhuoling2011/baidupcs-web] 错误代码: 50028, 消息: 系统繁忙，请稍候再试(50028) (#135)
我刚才也遇到了这个问题，测试了一下，发现是我密码错误多次被锁了。
建议可以尝试一下用账号密码直接登录百度云，看看是不是被锁了。
如果被锁了找回一下密码就行了。
