### ISSUE TITLE
3.6.5 无法远程使用

### ISSUE THREAD

**Issue by Explorer1092** [liuzhuoling2011/baidupcs-web#141]
貌似只能localhost使用？vps上需要设置转发才能使用。docker化以后，由于端口只监听127.0.0.1，导致无法远程暴漏端口。

**Comment by liuzhuoling2011** [comment]
其实是可以的， 我周末争取写一个教程出来

**Comment by Explorer1092** [comment]
> 其实是可以的， 我周末争取写一个教程出来

nginx也许可以，但是docker真的不行？你可以建一个docker试一下。

**Comment by Explorer1092** [comment]
> 其实是可以的， 我周末争取写一个教程出来

看到 --access 参数了 thx～
