### ISSUE TITLE
我用GO登录网盘提示“文件未授权”？怎么解决啊？

### ISSUE THREAD

**Issue by viytd** [liuzhuoling2011/baidupcs-web#142]
![11](https://user-images.githubusercontent.com/49066056/55231960-07ef3a00-525f-11e9-8a89-6f22736105e3.PNG)

用GO登录网盘后一片空白，看不到任何文件，是不是百度搞了新的限制措施了。。。

**Comment by liuzhuoling2011** [comment]
请参考 https://w.url.cn/s/AdjX09Y 用命令行设置appid
