### ISSUE TITLE
希望登录增加“记住我”功能

### ISSUE THREAD

**Issue by yuhr123** [liuzhuoling2011/baidupcs-web#143]
感谢作者的无私奉献！

在使用过程中发现 session 在大概24小时（个人估计的）后会清空，再次使用时就要重新授权登录。这个工具通常是个人或者家庭使用，可以考虑增加“记住我”的功能，提供1个月或更长的登录保持。从而避免经常性的重复登录。

**Comment by liuzhuoling2011** [comment]
你的观察力不错， 目前是1天过期，确实可以设置的更长一些，下一个版本改成30天吧
