### ISSUE TITLE
请问这个是怎么肥死啊？

### ISSUE THREAD

**Issue by 1045925330** [liuzhuoling2011/baidupcs-web#144]
错误代码: -1, 消息: 网络请求失败, Post https://wappass.baidu.com/wp/api/login: lookup wappass.baidu.com on [::1]:53: read udp [::1]:44293->[::1]:53: read: connection refused

我用的手机登的

**Comment by liuzhuoling2011** [comment]
应该是百度服务器抽风了吧，之后再试试
