### ISSUE TITLE
多帐号问题

### ISSUE THREAD

**Issue by sum198888** [liuzhuoling2011/baidupcs-web#145]
大佬，我用端口转发远程访问这个软件，结果我的账号登陆一次后别人账号就无法登陆了，可以到手机发送验证码这步，但输入验证码点登陆后又会跳转到原登录页面，请问怎样可以解决这个问题，谢谢！

**Comment by liuzhuoling2011** [comment]
可以删除设置中 配置文件目录 中的配置文件
就可以重新初始化了
