### ISSUE TITLE
网页版登陆之后没有任何文件，一片空白 

### ISSUE THREAD

**Issue by llr007** [liuzhuoling2011/baidupcs-web#148]
登录成功之后网盘内没有任何文件，试了360浏览器、IE浏览器、火狐浏览器，都是这样的。
界面有一句话File is not authoried。

**Comment by mianzhiyang** [comment]
+1

**Comment by liuzhuoling2011** [comment]
应该是appid不对， 可以用命令行重置一下appid
./BaiduPCS-Go config set -appid=266719

**Comment by mianzhiyang** [comment]
> 应该是appid不对， 可以用命令行重置一下appid
> ./BaiduPCS-Go config set -appid=266719

感谢，已解决
