### ISSUE TITLE
LEDE上搭建的baidupcs，用电脑无法访问

### ISSUE THREAD

**Issue by Enkannori** [liuzhuoling2011/baidupcs-web#156]
目前在用364版本，365及以上版本就会提示拒绝访问，baidupcs运营正常

**Comment by tianya908** [comment]
怎么搭建的

**Comment by Enkannori** [comment]
具体不是很清楚，koolshare的版本，软件中心里可以一键安装，然后升级是通过替换文件来完成

**Comment by liuzhuoling2011** [comment]
这个不清楚+1。。。

**Comment by liuzhuoling2011** [comment]
3.6.5以上版本默认开启了本地模式
需要远程访问的话， 需要在启动的时候加个参数 --access
详情可以参考：
https://w.url.cn/s/AdjX09Y
