### ISSUE TITLE
海外用户卡在登陆界面

### ISSUE THREAD

**Issue by PorridgeEater** [liuzhuoling2011/baidupcs-web#16]
坐标北美，登陆界面一直转圈，无法进入。
检测网络流量发现ws一直处于Pending状态
![image](https://user-images.githubusercontent.com/7046959/46922658-676fcb00-cfda-11e8-827d-d6a756aa0a80.png)

**Comment by PorridgeEater** [comment]
管理员模式运行解决了

**Comment by tonghs** [comment]
> 管理员模式运行解决了

@PorridgeEater 我也遇到了哎，麻烦问下，”管理员模式“具体是指啥啊？
