### ISSUE TITLE
HTTP 404错误

### ISSUE THREAD

**Issue by Alion548** [liuzhuoling2011/baidupcs-web#162]
![image](https://user-images.githubusercontent.com/8340545/56481524-1f35e600-64f2-11e9-942b-87eae800224f.png)
/img/logo.png
/img/icons/android-chrome-192x192.png
/dist/img/icons/favicon-32x32.png
/dist/img/icons/favicon-16x16.png

**Comment by liuzhuoling2011** [comment]
@loliconer 帮忙看看呗
