### ISSUE TITLE
FreeNAS，FreeBSD能不能运行？

### ISSUE THREAD

**Issue by ylzbhly** [liuzhuoling2011/baidupcs-web#163]
希望增加FreeNAS，FreeBSD运行方式，谢谢啦。

**Comment by liuzhuoling2011** [comment]
本质是linux，应该是可以的
![image](https://user-images.githubusercontent.com/8407297/56717362-13a32300-676f-11e9-9b9a-bce5873e59ef.png)

**Comment by ylzbhly** [comment]
./BaiduPCS-Go: Exec format error. Binary file not executable.
运行不了，是FreeNAS系统。
@liuzhuoling2011
