### ISSUE TITLE
经常添加不了下载任务

### ISSUE THREAD

**Issue by wuzhihuihui** [liuzhuoling2011/baidupcs-web#165]
有时已经有一个下载任务的时候，再下载其它的，提示添加到下载列表，但实际并没有。

**Comment by liuzhuoling2011** [comment]
是这样的， 前一个下载完成后会自动启动下一个下载列表任务的

**Comment by wuzhihuihui** [comment]
我发现了，有时它下载列表没显示，等下载完后，过一会就会自动添加到下载列表了。
