### ISSUE TITLE
可不可以做个Windows版的

### ISSUE THREAD

**Issue by so1999** [liuzhuoling2011/baidupcs-web#169]
Windows版怎么才能后台运行

**Comment by liuzhuoling2011** [comment]
这个不太清楚

**Comment by sukanka** [comment]
> Windows版怎么才能后台运行


**注意: 以下凡是涉及到路径的,请务必改成你自己的路径!**
# 后台运行

在 `BaiduPCG-Go` 的文件夹下新建一个 `hiderun.vbs` 文件, 内容如下
```
Set WshShell = WScript.CreateObject("WScript.Shell")
WshShell.Run "BaiduPCS-Go.exe",0
```
以后双击 `hiderun.vbs` 就可以后台运行.
# 自启动

将这个文件的**快捷方式**放到 `C:\ProgramData\Microsoft\Windows\Start Menu\Programs\StartUp` 下面可以自启动, 注意 `StatUp` 在中文系统中显示为 `启动`
![image](https://user-images.githubusercontent.com/31362108/59735399-0181c480-9288-11e9-893c-29e84f2e672c.png)

# 与 Aria2 公用一个脚本启动
不需要在 `BaiduPCS-Go` 的文件夹下建立 ` hiderun.vbs`, 而是在 ` Aria2` 的文件夹下建立 `hiderun.vbs`.

在 `hiderun.vbs` 中放入以下内容
```
dim fso,testfile
set fso = createobject("scripting.filesystemobject")
set testfile = fso.createtextfile("C:\Portable Software\Aria2\Aria2.log",True)
testfile.close

Set WshShell = WScript.CreateObject("WScript.Shell")
WshShell.Run "aria2c.exe --conf-path=aria2.conf",0

' Start BaiduPCS-Go
' Change directory.

WshShell.currentdirectory = "C:\Portable Software\BaiduPCS-Go"
WshShell.Run "BaiduPCS-Go.exe",0
```
然后把上面的 `hiderun.vbs` 的快捷方式放到 `C:\ProgramData\Microsoft\Windows\Start Menu\Programs\StartUp`
弄好了以后, 那个文件夹下应当只有一个 `hiderun.vbs` 的快捷方式.

最后 放一个我的截图

![`Aria2` 的文件夹](https://user-images.githubusercontent.com/31362108/59735748-7f929b00-9289-11e9-8341-a75ac0b75e92.png)
![`BaiduPCS-Go` 的文件夹](https://user-images.githubusercontent.com/31362108/59735761-8faa7a80-9289-11e9-8e48-cd98a845cd65.png)
![自启动](https://user-images.githubusercontent.com/31362108/59735399-0181c480-9288-11e9-893c-29e84f2e672c.png)

**Comment by liuzhuoling2011** [comment]
@sukanka 谢谢
