### ISSUE TITLE
帐号无法登陆

### ISSUE THREAD

**Issue by xxxyyy888** [liuzhuoling2011/baidupcs-web#172]

**Comment by liuzhuoling2011** [comment]
可以具体说明一下问题

**Comment by Ronny200** [comment]
> 可以具体说明一下问题

同样碰到这个问题，登录的时候登录按钮一直转圈圈

**Comment by xxxyyy888** [comment]
找到原因了，要设置一下帐号别名

**Comment by liuzhuoling2011** [comment]
#51 应该是同样的问题

**Comment by sostela** [comment]
> > 可以具体说明一下问题
> 
> 同样碰到这个问题，登录的时候登录按钮一直转圈圈

1. 之前多账号登陆
2. 都用BDUSS登录方式
3. 不显示已登陆列表

可能的解决方法：登陆最后一个未退出账号，BDUSS方式 ，未确定100%可行；如果用其他账号登陆 可能一直转圈圈。

**Comment by weituotian** [comment]
bduss登录不成功

**Comment by weituotian** [comment]
![image](https://user-images.githubusercontent.com/7270968/63633566-fdee2d80-c67c-11e9-83aa-37b6760c0923.png)
确认bduss正确，但是使用bduss，点击登录按钮，页面直接就刷新了，然后没效果

**Comment by weituotian** [comment]
@liuzhuoling2011
