### ISSUE TITLE
登陆后可以看到目录，但是每个文件夹的大小都是0B，请问怎么解决呢？

### ISSUE THREAD

**Issue by linxigjs** [liuzhuoling2011/baidupcs-web#173]
Ubuntu16.04,64位
[
![image](https://user-images.githubusercontent.com/24429575/57824863-15d92a00-77cf-11e9-9e36-58aa2c36637a.png)
](url)

**Comment by justincnn** [comment]
mac下也是这种情况，文件夹可以创建，但是无法下载任何文件啊。

**Comment by zhanglesheng** [comment]
一样的问题

**Comment by liuzhuoling2011** [comment]
文件夹大小百度返回的就是0B， 不过可以进去目录， 或者是直接下载的

**Comment by liuzhuoling2011** [comment]
无法下载可以检查一下下载目录的权限
appid是否正确
账号是否被百度临时限速，后台报错
