### ISSUE TITLE
无法登陆runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by CarlisleShaw** [liuzhuoling2011/baidupcs-web#174]
Get http://c.tieba.baidu.com/c/u/user/profile?has_plist=0&need_post_count=1&rn=1&uid=127655895&sign=971E0384A35270105719B7E653C29E53: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
2019/05/16 17:44:03 http: panic serving [::1]:57974: runtime error: invalid memory address or nil pointer dereference
goroutine 67 [running]:
net/http.(*conn).serve.func1(0xc00008f7c0)
	/usr/local/go/src/net/http/server.go:1746 +0xd0
panic(0x153b280, 0x1a695c0)
	/usr/local/go/src/runtime/panic.go:513 +0x1b9
github.com/iikira/BaiduPCS-Go/internal/pcsweb.WSLogin(0xc000960120, 0xc000962360, 0x0, 0x0)
	/mnt/hgfs/share/go/src/github.com/iikira/BaiduPCS-Go/internal/pcsweb/websocket.go:96 +0x442
github.com/iikira/BaiduPCS-Go/internal/pcsweb.WSHandler(0xc000960120)
	/mnt/hgfs/share/go/src/github.com/iikira/BaiduPCS-Go/internal/pcsweb/websocket.go:162 +0x367
golang.org/x/net/websocket.Server.serveWebSocket(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/mnt/hgfs/share/go/src/golang.org/x/net/websocket/server.go:89 +0x17e
golang.org/x/net/websocket.Handler.ServeHTTP(0x16031c8, 0x16793e0, 0xc000966460, 0xc00009d000)
	/mnt/hgfs/share/go/src/golang.org/x/net/websocket/server.go:112 +0x86
net/http.(*ServeMux).ServeHTTP(0x1a7d6e0, 0x16793e0, 0xc000966460, 0xc00009d000)
	/usr/local/go/src/net/http/server.go:2361 +0x127
net/http.serverHandler.ServeHTTP(0xc000165450, 0x16793e0, 0xc000966460, 0xc00009d000)
	/usr/local/go/src/net/http/server.go:2741 +0xab
net/http.(*conn).serve(0xc00008f7c0, 0x1679b60, 0xc00011ed40)
	/usr/local/go/src/net/http/server.go:1847 +0x646
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2851 +0x2f5

**Comment by liuzhuoling2011** [comment]
这个没有遇见过， 可能重启可以解决， 或者换个账号试试
