### ISSUE TITLE
3.6.7版本user not exist

### ISSUE THREAD

**Issue by kuyu132** [liuzhuoling2011/baidupcs-web#176]
使用最新的版本报user not exist，是用账户短信验证码登录的，退出再登录还是不行

**Comment by kuyu132** [comment]
看错了，应该是latest的版本，具体也不清楚多少版

**Comment by justincnn** [comment]
最近好像都没人维护了，哎

**Comment by siyisiyi** [comment]
一样的问题。

**Comment by lottelucky** [comment]
两种登陆方式都试过了，都是一样的错误信息，恳请作者尽快修复

**Comment by Blood3C** [comment]
同上，登陆后不显示主目录的文件名，浏览器提示user not exist，要刷新好几次才能正常显示。而且单击文件夹大概率不能进入下一级目录，只是屏幕闪一下。麻烦开发者大神百忙之余将bug修复。

**Comment by zhanglesheng** [comment]
一样的问题

**Comment by x-dr** [comment]
一样的问题

**Comment by code4lala** [comment]
一样的问题，恳请维护。

**Comment by CHEN1016** [comment]
好像是百度动手了

**Comment by dzefone** [comment]
看了下报错
说的是unexpected EOF
那样的话是不是可以加个重试，遇到EOF以后可以重试10次，10次全失败了再返回31045？

**Comment by chuanxinwong** [comment]
error_code: 31045
error_msg: "user not exists"
request_id: xxxxxxxxxxxx

**Comment by klfn** [comment]
user not exists

**Comment by liuzhuoling2011** [comment]
我刚刚试了我的账号， 用百度账号+密码+短信验证码登陆的
可以浏览文件，下载文件， 一切正常。。。

可以参考 https://github.com/iikira/BaiduPCS-Go/issues/711

**Comment by dzefone** [comment]
> 我刚刚试了我的账号， 用百度账号+密码+短信验证码登陆的
> 可以浏览文件，下载文件， 一切正常。。。
> 
> 可以参考 [iikira/BaiduPCS-Go#711](https://github.com/iikira/BaiduPCS-Go/issues/711)

并不是每次都出错，我这边感觉2/3情况会有出错
我个人觉着不知道具体原因的情况下加一个重试会好一点

**Comment by liuzhuoling2011** [comment]
更新了版本, 可以再试试有没有这个问题
我这边从来都没有出现过...
