### ISSUE TITLE
大神可以做一个限速的吗

### ISSUE THREAD

**Issue by gmshiwoge** [liuzhuoling2011/baidupcs-web#177]
谢谢大神开发好用工具
梅林路由器512内存 好像下载速度过快内存扛不这
希望可以设置下载限制功能

**Comment by gmshiwoge** [comment]
配置文件这里设置 "max_parallel": 1,
cpu就不会挤爆 原来是"max_parallel": 1000,的 cpu就会去到100%以后死机
设置"max_parallel": 1,就不会？

**Comment by liuzhuoling2011** [comment]
这个是开多少个线程的意思, 机器配置低的话, 少开些进程确实能解决问题
