### ISSUE TITLE
能否查看日志

### ISSUE THREAD

**Issue by godsped** [liuzhuoling2011/baidupcs-web#178]
现在百度限速，非付费会员当天下载超过一定大小（<8g)，或者可能进入黑名单用户，用第三方下载工具直接返回失败（不报错），我用arm版的baidupcs，一旦遇到这种情况后，在“上传下载管理”——我的下载——正在下载/已经完成里面就变空白了，什么也看不到，也不知道错误。  有什么地方可以查询日志的吗？

**Comment by liuzhuoling2011** [comment]
后台程序默认会打印信息的
如果是用docker的话, 估计要看docker log
