### ISSUE TITLE
设置http或https反向代理后无法访问了

### ISSUE THREAD

**Issue by CaoMeiYouRen** [liuzhuoling2011/baidupcs-web#180]
我希望通过域名来访问web端，但是貌似只能通过 ip+端口 建立连接，设置了代理后就不行了
用IP可以，域名不行，卡在登录上。
我一开始以为是我代理设置的问题，但是反复设置后还是无法解决。
代理的思路是外网通过域名访问，再转发到localhost:5299端口，理论上没什么问题啊？
```javascript
    proxy.web(req, res, { target: "http://localhost:5299", ws: true, changeOrigin: true, xfwd: true });//注意这里已经设置了ws的代理以及来源域名重写，理论上讲通过域名访问和直接用ip+端口访问效果一致
```
【服务器端显示】
Websocket新建连接: http://[本人域名]-> ws://localhost:5299/ws
Websocket连接断开: EOF
Websocket新建连接: https://[本人域名]-> ws://localhost:5299/ws
Websocket连接断开: EOF
【客户端显示】
Login.vue:174 Uncaught DOMException: Failed to execute 'send' on 'WebSocket': Still in CONNECTING state.

**Comment by onewayticket255** [comment]
我这里是ip/域名:5299 可以登录和下载
但是nginx转发(不带端口)可以登录却无法下载

**Comment by paulhybryant** [comment]
同样的问题。我用nginx做的反向代理，访问的时候得到的是一个空白页面。

**Comment by wlp7662973** [comment]
是啊,里面的js/css资源文件,都是用绝对路径访问的,使用Nginx的路径转向,全都404了

**Comment by hahach** [comment]
同样的问题，Nginx反向代理就只能打开看看，任何操作都无效

**Comment by hahach** [comment]
在其他人的issue下看到解决办法了，我用下面的配置可以使用
server {
    listen 80;
    listen [::]:80;
    server_name bd.lan;
    large_client_header_buffers 4 32k;
    location / {
                proxy_pass http://localhost:5299;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

location /ws {
                proxy_pass http://localhost:5299;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";

                proxy_connect_timeout 5s;
                proxy_read_timeout 30m;
                proxy_send_timeout 10s;
        }
}

**Comment by xiaozhikang0916** [comment]
请问能否通过修改配置的方式实现用相对路径获取资源？我用nginx做的通过路径的反向代理打不开web界面

**Comment by summitn** [comment]
![](https://img.waypons.com/imgs/2019/10/ebaae62622abdf24.png)

**Comment by liuzhuoling2011** [comment]
可以参考 #122
