### ISSUE TITLE
最新版265486 添加工作目录后速度非常慢

### ISSUE THREAD

**Issue by Skilling-Kiss** [liuzhuoling2011/baidupcs-web#181]
之前能用，但是需要把线程设置300，缓存设置88888，默认的不行，现在改成最大都没用了，下载速度还是限速100的样子。
![QQ截图20190530014448](https://user-images.githubusercontent.com/42971283/58579038-c7bb3080-827c-11e9-814e-fd3c41ede84f.png)
![QQ截图20190530014504](https://user-images.githubusercontent.com/42971283/58579044-cb4eb780-827c-11e9-939b-ac5f7166c5c0.png)

**Comment by Skilling-Kiss** [comment]
不知道是不是我重装过系统的原因，按理来说应该正常的，我换了一个账号结果怎么都不能改APPID，就放弃了，目前还没试过MAC和安卓还有IOS，大家的可以正常使用吗

**Comment by Skilling-Kiss** [comment]
![屏幕快照 2019-05-30 上午2 09 27](https://user-images.githubusercontent.com/42971283/58580657-3352cd00-8280-11e9-90ca-68cbf4efcca4.png)
Mac实测不行，速度依然不到100

**Comment by Asleep-Loneliness** [comment]
我前两天直接就下载不了，今天能下过了一会也被限速了

**Comment by Asleep-Loneliness** [comment]
感觉百度输入法这方法也被和谐了

**Comment by 1608637229** [comment]
最近被和谐了。这个输入法appid.现在是线程被限定死了。因此速度非常慢。
