### ISSUE TITLE
外网访问有些使用上的小问题请教 

### ISSUE THREAD

**Issue by Enkannori** [liuzhuoling2011/baidupcs-web#184]
我按照教程添加了--access参数，同时也可以外网访问，但是一旦关闭输入代码的界面就不能外网访问了，请问下是不是有类似结束设置之类的代码要输入？希望能一直外网访问
![image](https://user-images.githubusercontent.com/39235372/58645339-c39f1980-8335-11e9-9ede-3998b4425b56.png)

**Comment by Mint-M** [comment]
用screen操作，或者编写init.d脚本，作为服务器启动

**Comment by Enkannori** [comment]
好的 我去试试看
