### ISSUE TITLE
PCS应用ID找回

### ISSUE THREAD

**Issue by Ac310** [liuzhuoling2011/baidupcs-web#186]
本想按帖解决‘31326’问题，但显然，自己操作错误，没解决问题，反而：
因为将PCS应用ID改为265486，而未记下原始ID，现在改不会去了
虽然还能在localhost:5299登进账号，但所有文件、文件夹都看不见了
刷新页面，会显示'file is not authorized' 或 'pcs token not exist'
尝试改回ID，错误，显示“设置的appid不存在或不可读，请检查是否有权限”
请问有什么办法吗？谢谢。

**Comment by Skilling-Kiss** [comment]
APPID设为266719
并且把工作文件夹改回根目录应该就可以了

**Comment by Ac310** [comment]
> APPID设为266719
> 并且把工作文件夹改回根目录应该就可以了

好神奇！非常感谢！
