### ISSUE TITLE
速度仅比百度网盘限速模式快一丢丢,  百度网盘试用vip可以达到10MB/s

### ISSUE THREAD

**Issue by kwok-jh** [liuzhuoling2011/baidupcs-web#190]
![image](https://user-images.githubusercontent.com/37544880/60019889-75c1cb00-96c1-11e9-98c5-b820a1269266.png)

**Comment by liuzhuoling2011** [comment]
这个不做评价了, 取决于当前的网络环境
你也可以充个SVIP, 体验一下baidupcs带来的加速感~
