### ISSUE TITLE
不支持多用户同时登录操作吗？

### ISSUE THREAD

**Issue by leeloveying** [liuzhuoling2011/baidupcs-web#193]
在使用多个用户登录操作，后面登录的用户会把前面登录的用户冲掉，不知道是哪里的问题，是服务本身不支持多用户登录还是使用上有问题？求大神释疑

**Comment by liuzhuoling2011** [comment]
可以多账户切换, 不过运行的账户只能是一个
也就是说, 一个账户登录会T掉之前的账户
