### ISSUE TITLE
【求助】[1] 下载文件错误, 下载单个文件: 遇到错误, 远端服务器返回错误, 代码: 31326, 消息: user is not authorized, hitcode:104

### ISSUE THREAD

**Issue by Mitchell08** [liuzhuoling2011/baidupcs-web#196]
【求助】

按此方法设置了，但是返回错误。大佬们，请看看什么问题？

![1](https://user-images.githubusercontent.com/13077075/61451123-484c0280-a98b-11e9-81f0-94036b9e82b3.JPG)
![2](https://user-images.githubusercontent.com/13077075/61451124-48e49900-a98b-11e9-8ab0-a0665207dee1.JPG)
![3](https://user-images.githubusercontent.com/13077075/61451126-48e49900-a98b-11e9-8de8-6704e7b47ba6.JPG)

[1] 下载文件错误, 下载单个文件: 遇到错误, 远端服务器返回错误, 代码: 31326, 消息: user is not authorized, hitcode:104

**Comment by liuzhuoling2011** [comment]
貌似这个方法有时无效, 可以试试充个SVIP解封

**Comment by spldmanager** [comment]
我是svip账号，还是提示这个错误
