### ISSUE TITLE
安卓使用无法登录，出现错误代码:-1

### ISSUE THREAD

**Issue by Canaria21** [liuzhuoling2011/baidupcs-web#198]
安卓终端Termux里使用，在浏览器输入地址后出现 “错误代码：-1，消息：网络请求失败，Post https://wappass.baidu.com/wp/api/login:lookup wappass.baidu.com on[::1]：53：read udp[::1]：41542->[::1]：53：read：connection refused”

 多试了几次发现每次错误数字不一样，看图
![2](https://user-images.githubusercontent.com/52450169/62100138-fe381a80-b2c2-11e9-8bdd-0473b4517eb6.jpg)
![捕获](https://user-images.githubusercontent.com/52450169/62100139-0001de00-b2c3-11e9-9fc4-390bdacdaa55.JPG)

**Comment by liuzhuoling2011** [comment]
新版添加了对安卓的支持, 请下载安卓专用的版本
