### ISSUE TITLE
命令行部分功能被阉割了，是否可以恢复web和命令行同时工作

### ISSUE THREAD

**Issue by mpjanet** [liuzhuoling2011/baidupcs-web#199]
这一版把iikira/BaiduPCS-Go的命令行功能阉割掉了只保留了web以及几个配置相关命令，是否可以恢复为命令行和web同时工作。web界面从外网访问不到，而且web界面的实现不能配置反向代理子目录到5299端口，只能用命令行。

**Comment by liuzhuoling2011** [comment]
这个我觉得可以有

**Comment by liuzhuoling2011** [comment]
新版已经支持了
