### ISSUE TITLE
大神想问一下这个会不会触发限速

### ISSUE THREAD

**Issue by 1263892066** [liuzhuoling2011/baidupcs-web#200]
因为市面上大多方法最终基本都会触发百度云的限速，所以想问一下大神，这个模拟百度输入法生成在我的应用数据目录下生成一个baidu_shurufa的文件夹的方法比较另类，会不会触发百度云的限速？

**Comment by liuzhuoling2011** [comment]
使用量过大的话, 应该会触发, 正常情况下不会, 只不过速度慢了一点而已
想放心使用的话, 充个SVIP配合使用比较靠谱

________________________________
liuzhuoling2011@hotmail.com

发件人： 1263892066<mailto:notifications@github.com>
发送时间： 2019-08-04 23:40
收件人： liuzhuoling2011/baidupcs-web<mailto:baidupcs-web@noreply.github.com>
抄送： Subscribed<mailto:subscribed@noreply.github.com>
主题： [liuzhuoling2011/baidupcs-web] 大神想问一下这个会不会触发限速 (#200)

因为市面上大多方法最终基本都会触发百度云的限速，所以想问一下大神，这个模拟百度输入法生成在我的应用数据目录下生成一个baidu_shurufa的文件夹的方法比较另类，会不会触发百度云的限速？
