### ISSUE TITLE
Win版 怎么禁止外网访问？

### ISSUE THREAD

**Issue by lvxing8686** [liuzhuoling2011/baidupcs-web#201]
看说明 “对于Windows版的用户

双击打开程序默认开启了外网访问”

小白请问，Win版 怎么禁止外网访问？  最好，可以默认，一劳永逸。

**Comment by liuzhuoling2011** [comment]
![image](https://user-images.githubusercontent.com/8407297/63079994-77499a00-bf72-11e9-8610-496558504b88.png)
用命令行启动即可
