### ISSUE TITLE
releases里的mipsel拼错了..

### ISSUE THREAD

**Issue by KFERMercer** [liuzhuoling2011/baidupcs-web#203]
写了个脚本获取不到，细看才发现名字错了

**Comment by liuzhuoling2011** [comment]
刚刚检查了一遍, 没写错啊
go tool dist list 可以看到目前支持的系统,架构
输出如下:
android/386
android/amd64
android/arm
android/arm64
darwin/386
darwin/amd64
darwin/arm
darwin/arm64
dragonfly/amd64
freebsd/386
freebsd/amd64
freebsd/arm
linux/386
linux/amd64
linux/arm
linux/arm64
linux/mips
linux/mips64
linux/mips64le
linux/mipsle
linux/ppc64
linux/ppc64le
linux/s390x
nacl/386
nacl/amd64p32
nacl/arm
netbsd/386
netbsd/amd64
netbsd/arm
openbsd/386
openbsd/amd64
openbsd/arm
plan9/386
plan9/amd64
plan9/arm
solaris/amd64
windows/386
windows/amd64

**Comment by KFERMercer** [comment]
mipsle--->mipsel

**Comment by liuzhuoling2011** [comment]
linux/mipsle  在go的架构里, 它叫这个...
