### ISSUE TITLE
有木有老铁告诉我怎么后台运行

### ISSUE THREAD

**Issue by dacens** [liuzhuoling2011/baidupcs-web#205]
ssh运行它，窗口一关就挂了。咋整呢

**Comment by liuzhuoling2011** [comment]
远程机上安装tmux, 在tmux中运行就好了

**Comment by fuyukang** [comment]
nohup ./BaiduPCS-Go >/dev/null 2>&1 &

**Comment by Soys** [comment]
安装screen

**Comment by sakuramisaki** [comment]
nohup ./BaiduPCS-Go &

**Comment by liuzhuoling2011** [comment]
各位老铁都很给力~

**Comment by dacens** [comment]
> nohup ./BaiduPCS-Go >/dev/null 2>&1 &

感觉你这个比较靠谱，之前用nohup运行没带>也是不行
