### ISSUE TITLE
如何让程序使用本地访问，然后通过域名进行反代？

### ISSUE THREAD

**Issue by Soys** [liuzhuoling2011/baidupcs-web#208]
怎么让程序只能够在本地访问，然后通过反代使用？然后刚才通过域名反代后，刚输入用户名就会显示‘WebSocket连接发生错误 [object Event]’，这个问题如何解决？

**Comment by xiyionxiong** [comment]
nginx 配置如下
`     upstream baidupcs {
            server 127.0.0.1:5299;
       }
        server {
            listen       80;
            server_name  xx.xxx.xxx; # 域名
           location / {
                proxy_pass http://baidupcs;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location /ws {
                proxy_pass http://baidupcs;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";

                proxy_connect_timeout 5s;
                proxy_read_timeout 30m;
                proxy_send_timeout 10s;
        }
        }
`

**Comment by gkl1368** [comment]
最新的3.6.8好像不行了

**Comment by beckball** [comment]
> 最新的3.6.8好像不行了

可以使用 先在命令行 ./BaiduPCS-Go web 开启web UI之后再根据楼上转发设置

**Comment by liuzhuoling2011** [comment]
可以参考 #122
