### ISSUE TITLE
不能再openwrt中运行

### ISSUE THREAD

**Issue by gyflonely** [liuzhuoling2011/baidupcs-web#213]
我下载了源码用pandorbox19.02的SDK进行编译，Pandorabox应该是基于openwrt cc版的，内核为linux 3.14.79，编译完成安装后执行程序 显示程序错误，错误代码如下：
#BaiduPCS-Web web --port 5529 --access
打开浏览器, 输入: http://localhost:5529 查看效果
panic: could not locate box "dist"

goroutine 1 [running]:
github.com/iikira/BaiduPCS-Go/vendor/github.com/GeertJohan/go%2erice.MustFindBox(0x5f6c70, 0x4, 0x4)
        /mnt/c/Users/zoran.liu/go/src/github.com/iikira/BaiduPCS-Go/vendor/github.com/GeertJohan/go.rice/box.go:110 +0xb0
github.com/iikira/BaiduPCS-Go/internal/pcsweb.StartServer(0x1599, 0x5f8401, 0x6, 0x1501)
        /mnt/c/Users/zoran.liu/go/src/github.com/iikira/BaiduPCS-Go/internal/pcsweb/pcsweb.go:21 +0x60
main.main.func2(0x8ecc2c0, 0x0, 0x8ecc2c0)
        /mnt/c/Users/zoran.liu/go/src/github.com/iikira/BaiduPCS-Go/main.go:129 +0x124
github.com/iikira/BaiduPCS-Go/vendor/github.com/urfave/cli.HandleAction(0x55dc20, 0x621080, 0x8ecc2c0, 0x8e15200, 0x0)
        /mnt/c/Users/zoran.liu/go/src/github.com/iikira/BaiduPCS-Go/vendor/github.com/urfave/cli/app.go:490 +0x10c
github.com/iikira/BaiduPCS-Go/vendor/github.com/urfave/cli.Command.Run(0x5f682b, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x603c48, 0x14, 0x0, ...)
        /mnt/c/Users/zoran.liu/go/src/github.com/iikira/BaiduPCS-Go/vendor/github.com/urfave/cli/command.go:210 +0x88c
github.com/iikira/BaiduPCS-Go/vendor/github.com/urfave/cli.(*App).Run(0x8e01a40, 0x8e14030, 0x5, 0x6, 0x0, 0x0)
        /mnt/c/Users/zoran.liu/go/src/github.com/iikira/BaiduPCS-Go/vendor/github.com/urfave/cli/app.go:255 +0x584
main.main()
        /mnt/c/Users/zoran.liu/go/src/github.com/iikira/BaiduPCS-Go/main.go:1284 +0x3b14
请问这个问题如何解决，我google了一下，看到有个filebrower的程序也出现类似这个问题，是修改了源码中一个go文件的dist路径，baidupcs-web中没有看到有go文件，有个vue.config.js里面有个dist不知道是不是这个，小白一个，请指教
ps:程序命令行可以执行，就是原版的命令可以执行，就是BaiduPCS-web web这个命令执行会出上述错误，localhost:5299也开不开

**Comment by liuzhuoling2011** [comment]
我感觉不用源码编译吧， 把release里面那几个linux的版本试一下？
