### ISSUE TITLE
 输入的本地文件夹路径错误，请检查目录是否存在或者具有可写权限

### ISSUE THREAD

**Issue by liangliyong25** [liuzhuoling2011/baidupcs-web#218]
输入的本地文件夹路径错误，请检查目录是否存在或者具有可写权限
请问怎么解决

**Comment by tinzang** [comment]
appid又挂了吧

**Comment by menghuanzhixiang** [comment]
> 输入的本地文件夹路径错误，请检查目录是否存在或者具有可写权限
> 请问怎么解决

就是目录没权限，给下载目录777权限

**Comment by liangliyong25** [comment]
> > 输入的本地文件夹路径错误，请检查目录是否存在或者具有可写权限
> > 请问怎么解决
> 
> 就是目录没权限，给下载目录777权限

我不是想下载到服务器，而是下载到本地电脑里。

**Comment by liuzhuoling2011** [comment]
> > > 输入的本地文件夹路径错误，请检查目录是否存在或者具有可写权限
> > > 请问怎么解决
> > 
> > 
> > 就是目录没权限，给下载目录777权限
> 
> 我不是想下载到服务器，而是下载到本地电脑里。

那可以在本地电脑启动程序
