### ISSUE TITLE
登陆后无法进入页面

### ISSUE THREAD

**Issue by dreamer2qian** [liuzhuoling2011/baidupcs-web#22]
![a](https://user-images.githubusercontent.com/27912002/47263512-7a801f00-d535-11e8-9313-5cfa7191236d.png)

如图，登陆后无法进入百度云。只能停留在登陆页面。
我试了很多平台（windows 10 64位,linux ubuntu 16.04 64位，armv7）全都是这种情况，
我不知道什么原因？是我频繁登陆导致？

**Comment by dreamer2qian** [comment]
好吧，其实用命令行下的客服端是没有问题的。

**Comment by liuzhuoling2011** [comment]
这个问题很奇怪, 我没有遇见过诶
有试过其他账号能登陆吗

**Comment by liuzhuoling2011** [comment]
收到, 感谢分析
