### ISSUE TITLE
无法在Web配置页面修改配置

### ISSUE THREAD

**Issue by zombie110year** [liuzhuoling2011/baidupcs-web#23]
系统: Windows10
Baidupcs-web 版本: 3.5.7
---
下载了 [BaiduPCS-Go-3.5.7-windows-amd64](http://oozw0y5q9.bkt.clouddn.com/BaiduPCS-Go-3.5.7-windows-amd64.zip) 发现在网页的"设置"界面的修改无法保存, 退出界面后所有配置项恢复原状, 最终是通过修改 `BAIDUPCS_GO_CONFIG_DIR` 下的 ` pcs_config.json` 才成功修改了 appid 配置.

**Comment by liuzhuoling2011** [comment]
不错不错, 可以自行修改pcs_config.json
无法保存提示的错误是什么呢? 可以检查一下"下载目录是否存在或者目录是否可写"
