### ISSUE TITLE
release界面别发政治相关哦

### ISSUE THREAD

**Issue by HolyGod33** [liuzhuoling2011/baidupcs-web#230]

**Comment by stalkercn** [comment]
刘卓灵？在gayhub抖机灵   想出名我可以帮你

**Comment by liuzhuoling2011** [comment]
> 刘卓灵？在gayhub抖机灵 想出名我可以帮你

没有想靠这个出名哈, 只是当时觉得应该支持一下香港政府, 希望早日恢复繁荣

@HolyGod33 谢谢提醒, 之后我注意一下

**Comment by liuzhuoling2011** [comment]
@stalkercn 话说你认识我?
