### ISSUE TITLE
无法获取文件目录

### ISSUE THREAD

**Issue by sonicviking** [liuzhuoling2011/baidupcs-web#239]
登录进入后出现 file is not authorized,不能获得文件目录，换了不同账号都是这个错误。x86 和 64位版本都试过了，一样的错误。请问怎么解决？
![微信截图_20191101090256](https://user-images.githubusercontent.com/4038338/67995742-09666200-fc87-11e9-872d-e55b8243958f.png)

**Comment by liuzhuoling2011** [comment]
估计是appid的问题, 建议看公众号的介绍文章, 把appid还原

________________________________
liuzhuoling2011@hotmail.com

发件人： sonicviking<mailto:notifications@github.com>
发送时间： 2019-11-01 09:08
收件人： liuzhuoling2011/baidupcs-web<mailto:baidupcs-web@noreply.github.com>
抄送： Subscribed<mailto:subscribed@noreply.github.com>
主题： [liuzhuoling2011/baidupcs-web] 无法获取文件目录 (#239)

登录进入后出现 file is not authorized,不能获得文件目录，换了不同账号都是这个错误。x86 和 64位版本都试过了，一样的错误。请问怎么解决？
[微信截图_20191101090256]<https://user-images.githubusercontent.com/4038338/67995742-09666200-fc87-11e9-872d-e55b8243958f.png>

**Comment by sonicviking** [comment]
那么估计是appid设置错误，请在命令行下执行

./BaiduPCS-Go config set -appid=266719
------------------------------

你说的是这个吧？请问这个是在哪里输入？我不懂程序……我的系统是win10
