### ISSUE TITLE
在小米路由器arm上运行失败！

### ISSUE THREAD

**Issue by monlor** [liuzhuoling2011/baidupcs-web#24]
提示could not locate box "static"

**Comment by liuzhuoling2011** [comment]
这个就有些尴尬了, 没有小米路由器, 测试不了

**Comment by monlor** [comment]
你qq多少，我们来远程一下？

**Comment by monlor** [comment]
或者可以跟我说说这个是什么原因导致的，这个静态资源怎么加载的

**Comment by liuzhuoling2011** [comment]
这个有点儿复杂, 远程估计也不好解决
静态资源怎么加载的, 可以给你看一段代码
https://github.com/liuzhuoling2011/BaiduPCS-Go/blob/master/internal/pcsweb/pcsweb.go

**Comment by Hylocereus0011** [comment]
你是米路由什么型号的？我小米路由3用mipsle版成功启动

**Comment by testiknn** [comment]
先搞清设备的CPU架构再说。
小米路由器CPU是MTK7620或7621。属于mipsle架构。不是arm。

**Comment by monlor** [comment]
@testiknn 老哥，你用过所有的小米路由器？   然后现在运行又没问题了，不知是否是账号问题，下载东西没进度。
