### ISSUE TITLE
登录成功后，主目录下是空的。

### ISSUE THREAD

**Issue by kingdom031** [liuzhuoling2011/baidupcs-web#248]
登录成功后，主目录下是空的。
![image](https://user-images.githubusercontent.com/6457814/69298629-74cd9f00-0c49-11ea-841c-b9b7213dff4e.png)
![image](https://user-images.githubusercontent.com/6457814/69299477-9760b780-0c4b-11ea-84e0-4b06f3d960fc.png)

**Comment by liuzhuoling2011** [comment]
应该是appid设置的不对
