### ISSUE TITLE
能否出个完整的编译打包教程

### ISSUE THREAD

**Issue by wenjunzhangp** [liuzhuoling2011/baidupcs-web#249]
针对此web项目，和后台golang项目，能出个详细的打包部署教程吗，不胜感激

**Comment by liuzhuoling2011** [comment]
最近有些忙, 有时间一定写一下

**Comment by wenjunzhangp** [comment]
我在本地将前后台打包成了sh，但是往服务器部署vue前端资源总是会报错，您有空的话能帮忙看下哪里的问题吗？xaim下面我把报错截图出来，点击登录和bduss登录都会出现这个问题。
![image](https://user-images.githubusercontent.com/36065067/70406277-2b6bb500-1a7b-11ea-8c63-2cd0a6beede6.png)

**Comment by wenjunzhangp** [comment]
这是我的打包步骤：

1. `cmd` 切换到路径 `BaiduPCS-Go\internal\pcsweb` 下，执行 `rice embed-go` 命令。
2. 执行`build_linux.sh` 脚本文件，将生成后的 `main` 二进制文件重命名为 `main.sh`，上传到`linux`，分别执行 `chmod 777 main.sh`、`chmod u+x main.sh` 。
`build_linux.sh` 内容如下：
`GOOS=linux GOARCH=amd64 go build -ldflags "-s -w" main.go`

**Comment by wenjunzhangp** [comment]
改了部分`vue`和`go`代码，本地和服务器均正常了。

**Comment by haoboy78** [comment]
@wenjunzhangp 请教下我改了部分vue代码，如何在我本机mac上跑起来？
