### ISSUE TITLE
NAS docker下载文件错误，x509: failed to load system roots and no roots provided

### ISSUE THREAD

**Issue by pennywu2016** [liuzhuoling2011/baidupcs-web#260]
请问怎么解决，谢谢。

**Comment by SuperNG6** [comment]
没有配置PUID，PGID，可以试试我这个镜像
https://hub.docker.com/r/superng6/baidupcs-web

**Comment by pennywu2016** [comment]
> 没有配置PUID，PGID，可以试试我这个镜像
> https://hub.docker.com/r/superng6/baidupcs-web

非常感谢，可以使用了，不过SVIP下载也只有100k左右了

**Comment by liuzhuoling2011** [comment]
https://github.com/iikira/BaiduPCS-Go/issues/858
貌似加上 -locate 会快很多
