### ISSUE TITLE
登录失败

### ISSUE THREAD

**Issue by qinxiaowen** [liuzhuoling2011/baidupcs-web#261]
错误代码: -1, 消息: 网络请求失败, Post https://wappass.baidu.com/wp/api/login: lookup wappass.baidu.com on [fe80::1]:53: write udp [fe80::ca1:e105:3a78:465a%en0]:63552->[fe80::1]:53: write: no route to host
![image](https://user-images.githubusercontent.com/8536046/71639704-4dd9a280-2cb6-11ea-8ad2-c0e7154718b0.png)

**Comment by liuzhuoling2011** [comment]
和 #264 重复了
