### ISSUE TITLE
3.7.0无法登陆

### ISSUE THREAD

**Issue by rt265** [liuzhuoling2011/baidupcs-web#265]
错误代码: -1, 消息: 网络请求失败, Post https://wappass.baidu.com/wp/api/login: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

**Comment by liuzhuoling2011** [comment]
我之前也试过几次, 貌似是百度网络抽风

**Comment by liuzhuoling2011** [comment]
和 #264 重复了
