### ISSUE TITLE
无法下载文件

### ISSUE THREAD

**Issue by petrellisome** [liuzhuoling2011/baidupcs-web#28]
![_20181025151807](https://user-images.githubusercontent.com/44460145/47482445-280e6d80-d869-11e8-838b-976f28ca67ee.png)
![_20181025151936](https://user-images.githubusercontent.com/44460145/47482486-483e2c80-d869-11e8-82b6-2229c7fd01a7.png)
昨天刚批量下载了一些，突然发现创建下载任务后无法下载，但文件已经创建，如上图示，请问是什么问题

**Comment by ozrarb** [comment]
我也有同樣的問題

**Comment by liuzhuoling2011** [comment]
"目前百度是针对账号进行限速，当一个非会员账号下载量达到一定阈值就会触发限速。账号被限速之后容易出现下载错误、掉连接数等问题，需要过几天或者开通会员才会恢复。"

**Comment by liuzhuoling2011** [comment]
今天更新一下, 给出一个解决方案

**Comment by adim421** [comment]
下了一会儿就不能下了

**Comment by liuzhuoling2011** [comment]
#59  一样的问题， 这个close了
