### ISSUE TITLE
 如何以分享的方式下载文件

### ISSUE THREAD

**Issue by typesly** [liuzhuoling2011/baidupcs-web#29]
我用的是MACOS,在baidupcs-go中,可以用--share参数来以分享文件的方式下载，在这里完全找不到这个选项。是没有实现这个功能还是我没找到呢?

**Comment by liuzhuoling2011** [comment]
这个目前没有做, 都是以默认的形式下载
今天有时间的话, 更新一波

**Comment by liuzhuoling2011** [comment]
后台已经更新， 下一次发布就可以使用了

**Comment by user1121114685** [comment]
> 后台已经更新， 下一次发布就可以使用了

大佬请教如何进行分享下载呢？
