### ISSUE TITLE
BUG修复版本-已开源-有问题请先使用这个版本

### ISSUE THREAD

**Issue by Erope** [liuzhuoling2011/baidupcs-web#290]
主要修复三个问题:
1. 修复账户密码登录问题(验证码处理有误，导致无法获取验证码)
2. 下载在无下载参数情况下(分享下载/locate下载/默认下载)，默认使用locate方式下载，以获取更高的速度，非SVIP会员注意可能触发限速。
3. 修复刷新后无法获取原来下载中数据

增加功能:
1. 推送到Aria2下载功能

没有压缩，所以有点大
没有编译安卓的，没环境

https://github.com/Erope/baidupcs-web/

**Comment by Erope** [comment]
如此版本有致命问题，请在下方留言，谢谢

**Comment by FaceChan** [comment]
感谢分享。测试openwrt可用

**Comment by gzz2000** [comment]
可以交个pull request？

**Comment by Erope** [comment]
> 楼主要不要考虑交一个pull request，或者fork一个分支

不准备，没有长期维护打算，只是用着不太舒服，自己改了一丢丢

**Comment by paldier** [comment]
说一下修改方法吧

**Comment by wwoody** [comment]
替换后可用，希望说下修改方法。

**Comment by Erope** [comment]
> 说一下修改方法吧

修改了一个文件，已经在蓝奏云上了，没有使用git方式提前抱歉，因为只是小修改

**Comment by Erope** [comment]
> 替换后可用，希望说下修改方法。

修改了一个文件，已经在蓝奏云上了，没有使用git方式提前抱歉，因为只是小修改

**Comment by paldier** [comment]
已经帮忙提交

**Comment by Erope** [comment]
> 已经帮忙提交

好的，谢谢。现在最大的问题其实是WS造成的数据不持续，希望有人修复一下。

**Comment by FaceChan** [comment]
> > 已经帮忙提交
> 
> 好的，谢谢。现在最大的问题其实是WS造成的数据不持续，希望有人修复一下。

用了2天，被限速了。。。看来还是被发现了

**Comment by Roywaller** [comment]
![image](https://user-images.githubusercontent.com/12166398/78349943-f27dc000-75d6-11ea-829a-fd5d88192c91.png)
环境Linux raspberrypi 4.13.16 #2 Mon Dec 18 21:40:00 CST 2017 armv6l

**Comment by Erope** [comment]
> > > 已经帮忙提交
> > 
> > 
> > 好的，谢谢。现在最大的问题其实是WS造成的数据不持续，希望有人修复一下。
> 
> 用了2天，被限速了。。。看来还是被发现了

限速是进小黑屋了，解析出来的是限速服务器，一般冲SVIP可以解决

**Comment by Erope** [comment]
> ![image](https://user-images.githubusercontent.com/12166398/78349943-f27dc000-75d6-11ea-829a-fd5d88192c91.png)
> 环境Linux raspberrypi 4.13.16 #2 Mon Dec 18 21:40:00 CST 2017 armv6l

实在抱歉，手中暂时没有ARM设备，树莓派放学校了

**Comment by hue715** [comment]
验证码错误2次，使用邮箱获取验证码失败，应该是没有发出验证码请求。

**Comment by Erope** [comment]
更新BDUSS的错误输出，见 #289 
使用没问题的不需要更新

**Comment by Erope** [comment]
> 更新BDUSS的错误输出，见 #289
> 使用没问题的不需要更新

修改文件: https://github.com/Erope/baidupcs-web

**Comment by Erope** [comment]
紧急修复了无法发送验证码问题，见 https://github.com/iikira/Baidu-Login/pull/7
推荐更新

**Comment by AhFook** [comment]
谢谢啊，这程式十分好用！
运行时偶然看到一段好像关于「香港加油」的讯息，未及细读已消失。想再细看已无办法。可以告诉我怎样查看内容吗？

**Comment by Erope** [comment]
> 谢谢啊，这程式十分好用！
> 运行时偶然看到一段好像关于「香港加油」的讯息，未及细读已消失。想再看已无办法。可以告诉我怎样查看内容吗？

那个应该是原作者就有的？很抱歉我没找到...
原作者的Release界面倒是有

**Comment by AhFook** [comment]
Thanks for your reply, Erope  :)

**Comment by leoatchina** [comment]
谢谢！

**Comment by liuzhuoling2011** [comment]
> 谢谢啊，这程式十分好用！
> 运行时偶然看到一段好像关于「香港加油」的讯息，未及细读已消失。想再看已无办法。可以告诉我怎样查看内容吗？

那个是推送的消息

**Comment by liuzhuoling2011** [comment]
> 谢谢啊，这程式十分好用！
> 运行时偶然看到一段好像关于「香港加油」的讯息，未及细读已消失。想再看已无办法。可以告诉我怎样查看内容吗？

那个是推送的消息, 当时香港挺乱的, 希望早日恢复和平/经济繁荣

**Comment by 338317** [comment]
希望可以增加下载完成后调用脚本的功能，用来实现自动上传onedrive，虽然可以通过aria2间接调用上传脚本，不过用aria2经常会下载失败

**Comment by Erope** [comment]
> 希望可以增加下载完成后调用脚本的功能，用来实现自动上传onedrive，虽然可以通过aria2间接调用上传脚本，不过用aria2经常会下载失败

可以使用rclone挂载目录并直接进行上传

**Comment by Erope** [comment]
项目需要

**Comment by liuran001** [comment]
大佬删库了吗?

**Comment by Erope** [comment]
> 大佬删库了吗?

是的

**Comment by jackgaoyichen** [comment]
> > 大佬删库了吗?
> 
> 是的

大佬还有办法使用到你更新的程序吗

**Comment by Erope** [comment]
> > > 大佬删库了吗?
> > 
> > 
> > 是的
> 
> 大佬还有办法使用到你更新的程序吗

https://www.shinenet.cn/archives/131.html
