### ISSUE TITLE
有没有配置界面呢

### ISSUE THREAD

**Issue by wwqgtxx** [liuzhuoling2011/baidupcs-web#3]
我看了[你的BaiduPCS-Go的提交记录](https://github.com/iikira/BaiduPCS-Go/compare/master...liuzhuoling2011:master)，发现后端是有config接口的，那么请问前端的配置界面是还没写么

**Comment by wwqgtxx** [comment]
好吧，找了一下dom树，发现还真的有
```html
<li data-v-5649043e="" class="ivu-menu-submenu ivu-menu-item-active ivu-menu-child-item-active"><div class="ivu-menu-submenu-title"><i data-v-5649043e="" class="ivu-icon ivu-icon-md-person"></i><i class="ivu-icon ivu-icon-ios-arrow-down ivu-menu-submenu-title-icon"></i></div> <div class="ivu-select-dropdown" style="min-width: 199.156px; transform-origin: center top 0px; display: none;"><ul class="ivu-menu-drop-list"> <li data-v-5649043e="" class="ivu-menu-item">简介</li> <li data-v-5649043e="" class="ivu-menu-item ivu-menu-item-active ivu-menu-item-selected">设置</li> <li data-v-5649043e="" class="ivu-menu-item">退出</li></ul></div></li>
```
不过是不是应该改一下css，这个在我这边根本就看不到这个元素。。

**Comment by wwqgtxx** [comment]
可能需要考虑一下低分辨率的屏幕，我这里分辨率为1440*900的屏幕上根本就不显示右上角的那一部分元素

**Comment by liuzhuoling2011** [comment]
谢谢提醒 , 我今天看看, 改进一下

**Comment by liuzhuoling2011** [comment]
![image](https://user-images.githubusercontent.com/8407297/45582023-4e8cd080-b8db-11e8-8702-51a87ef377c3.png)
我试了一下, 貌似没问题的, 你是不是开启了网页放大效果了

**Comment by wwqgtxx** [comment]
![image](https://user-images.githubusercontent.com/582584/45582037-a62b3c00-b8db-11e8-8f0d-e8c06cba6e44.png)

没有，我在chrome69下实验的，完全被挤到了旁边，是不是和用户名长度也有一定的关系

**Comment by wwqgtxx** [comment]
刚才手动改了一下dom，发现当用户名长度大于10的时候这个项就不可见了

**Comment by wwqgtxx** [comment]
![image](https://user-images.githubusercontent.com/582584/45582070-379aae00-b8dc-11e8-8aab-d283ab52e6d7.png)
![image](https://user-images.githubusercontent.com/582584/45582071-3ff2e900-b8dc-11e8-905a-39f518470066.png)

**Comment by liuzhuoling2011** [comment]
还真是这个问题...我看看怎么fix, 谢啦

**Comment by liuzhuoling2011** [comment]
#6 已经改好了
