### ISSUE TITLE
请问这个错误是什么原因？

### ISSUE THREAD

**Issue by GreatDick** [liuzhuoling2011/baidupcs-web#30]
任务结束, 时间: 30.114s, 数据总量: 0B
以下文件下载失败: 
  0  /6.0/GAPPS/open_gapps-arm-6.0-mini-20160320.zip  
Websocket连接断开: EOF
Websocket连接断开: EOF
Websocket新建连接: http://192.168.1.239:5299 -> ws://192.168.1.239:5299/ws
Websocket连接断开: EOF

**Comment by shineben** [comment]
同样问题

**Comment by loliconer** [comment]
不太清楚，今天也发现下载不了，很有可能被封了。

**Comment by nicedayever** [comment]
同样无法下载文件，是不是已经被封？

**Comment by liuzhuoling2011** [comment]
#28 同样的issue
