### ISSUE TITLE
小米路由器3使用mipsle版遇到的一些问题

### ISSUE THREAD

**Issue by Hylocereus0011** [liuzhuoling2011/baidupcs-web#32]
添加下载内容以后在下载管理看不到正在下载的内容，但根据小米路由器APP的网络监控，文件其实是在正常下载的

**Comment by Hylocereus0011** [comment]
[
![screenshot_2018-10-28-09-40-04-589_org connectbot](https://user-images.githubusercontent.com/42207329/47610976-83bd3e80-da95-11e8-98e2-26171a79130d.png)
](url)

**Comment by liuzhuoling2011** [comment]
这个和 #28 很像
