### ISSUE TITLE
怎么在其他平台使用

### ISSUE THREAD

**Issue by jth445600** [liuzhuoling2011/baidupcs-web#4]
有没有什么编译交叉编译或文档，我想编译了在树莓派上用，都需要什么环境啊？

**Comment by liuzhuoling2011** [comment]
我在baidupcs-go 后台提交的pr还没有被批准, 所以暂时是没有交叉编译的文档, 我可以直接编一个放在release里面

**Comment by liuzhuoling2011** [comment]
在release里面新增了arm版, 可以试试

**Comment by jth445600** [comment]
不用在手机平板上的chrome浏览器上使用，只显示左边一部分。希望改进一下。我下午虽然说树大招风，但是界面做的很好，确实比命令行来的方便，我还是支持的。

**Comment by liuzhuoling2011** [comment]
目前手机版的页面还没做， 可以考虑一下
