### ISSUE TITLE
无法查看下载任务

### ISSUE THREAD

**Issue by ChuHuaiJin** [liuzhuoling2011/baidupcs-web#42]
同时下载任务过多时无法查看下载任务列表，列表为空。

**Comment by armincxh** [comment]
我也有这种情况。。。后来在终端查看是获取文件失败，我可以进行别的操作就是不能下载文件，可能被百度限制了😂

**Comment by ChuHuaiJin** [comment]
这就很尴尬了🤣🤣

发自我的 iPhone

**Comment by loliconer** [comment]
感谢反馈，是个bug，下个版本修复。
