### ISSUE TITLE
用这个看文件的大小和文件的实际大小不一样

### ISSUE THREAD

**Issue by 1608637229** [liuzhuoling2011/baidupcs-web#44]
查看网盘里的文件比如实际上238M，这个显示242.这个是1000作为了单位而不是1024吧。下载的时候显示的大小是正确的。但是一个260M的文件却又显示为了277M。不知道是不是bug.总之就是所有的文件都显示偏大了。

**Comment by 1608637229** [comment]
还有新版本多个文件下载看不到待下载的列表了。只能下过一个才显示下一个文件。且看不到文件的名称。

**Comment by loliconer** [comment]
> 还有新版本多个文件下载看不到待下载的列表了。只能下过一个才显示下一个文件。且看不到文件的名称。
> 出现了两次又恢复正常了，也可能是我网络不太稳定的缘故。

感谢反馈。因为现在是同一时间只能下载一个文件，所以只显示了一个，后面会改进。

**Comment by loliconer** [comment]
> 还有新版本多个文件下载看不到待下载的列表了。只能下过一个才显示下一个文件。且看不到文件的名称。
> 出现了两次又恢复正常了，也可能是我网络不太稳定的缘故。

感谢反馈，是个bug，下个版本修复。

**Comment by AlleNPooh** [comment]
在我的页面里是不显示文件夹大小的，怎么回事儿

**Comment by liuzhuoling2011** [comment]
已经修复
