### ISSUE TITLE
我有个帐号怎么登陆不上去

### ISSUE THREAD

**Issue by imj2** [liuzhuoling2011/baidupcs-web#51]
我有个帐号怎么登陆不上去，其他帐号都可以正常登陆，这个帐号一输入验证码后就直接跳转到登陆页面，然后右边的已登录用户列表就消失了！

帐号绑定了手机与邮箱的，直接登陆正常可以，使用BaiduPCS-Go.exe就不能登陆了！

这个是截图说明！
https://img.alicdn.com/imgextra/i3/95249875/O1CN01PEzjnG2MoncoZrOxq_!!95249875.jpg

**Comment by chenhui7373** [comment]
限号

**Comment by fwnl** [comment]
我新注册的百度盘账号也是这样，登录成功后进不去，又跳到登陆界面，但是这个账号在PanDownload软件上登陆没什么问题

**Comment by liuzhuoling2011** [comment]
之前有人解决了, 看看是不是这个问题
![image](https://user-images.githubusercontent.com/8407297/48455155-07e12700-e7f5-11e8-9c8f-de7d519ec4c6.png)

**Comment by fwnl** [comment]
果然是新账号没有设置名字导致，给用手机号注册的新账号起个名字就可以了

**Comment by 652626737** [comment]
我添加完下载任务后，一刷新界面任务全部消失了，这个是什么原因

**Comment by islandlxl** [comment]
我下载的根本就不能使用BDUSS登录

**Comment by qq471754603** [comment]
MAC端，登陆一直转，登不上去啊

**Comment by sunnyangazy** [comment]
您好，登陆时显示网络错误，是什么原因呢

**Comment by z66666** [comment]
登陆不上呀
BDUSS登陆只是刷新一下网页

**Comment by Luao1104** [comment]
Windows登录一直转圈，设置了用户名也不行啊！！！
