### ISSUE TITLE
liunx下没有收到验证码

### ISSUE THREAD

**Issue by 61128** [liuzhuoling2011/baidupcs-web#53]
我把程序部署到阿里云ecs上 然后远程访问 登录的时候到最后一步 需要验证码 提示是发送了 但是我手机并没有收到 然后我测试了我本机win版本的 是正常的 在cmd里面提示消息：验证码已发送  但是在liunx里面就提示消息：未知消息  liunx系统是CentOS7.4 里面安装了并运行了nginx服务器 是不是冲突了 还是说我只开了5299端口 是端口挡住了？

**Comment by liuzhuoling2011** [comment]
不好意思, 不太方便
