### ISSUE TITLE
经常下载失败是什么问题啊？

### ISSUE THREAD

**Issue by imj2** [liuzhuoling2011/baidupcs-web#54]
经常下载失败是什么问题啊？

**Comment by liuzhuoling2011** [comment]
"目前百度是针对账号进行限速，当一个非会员账号下载量达到一定阈值就会触发限速。账号被限速之后容易出现下载错误、掉连接数等问题，需要过几天或者开通会员才会恢复。"

**Comment by liuzhuoling2011** [comment]
#28 一样的issue
