### ISSUE TITLE
下载地址被ESET拉黑了。

### ISSUE THREAD

**Issue by Gokou-Ruri** [liuzhuoling2011/baidupcs-web#60]
个人建议还是用gayhub，或者双源，七牛做备份？

![image](https://user-images.githubusercontent.com/26711804/48841574-c4765200-edcc-11e8-9f95-bf7f33639881.png)
![image](https://user-images.githubusercontent.com/26711804/48841594-d6f08b80-edcc-11e8-93b0-522ce74edba3.png)

**Comment by liuzhuoling2011** [comment]
嗯嗯， 以后发布的时候github也上传一份吧
