### ISSUE TITLE
能否适配移动端浏览器呢？

### ISSUE THREAD

**Issue by kangyu1230** [liuzhuoling2011/baidupcs-web#62]
PC上用着很棒，但在手机浏览器上，比如iOS Safari或者Android Chrome，排版会错乱，界面上有些元素会错位、显示不全或者在界面外无法交互。大佬有时间的话考虑一下吧😄

**Comment by liuzhuoling2011** [comment]
嗯嗯， 这个会考虑的， 不过没那么快

**Comment by usjinbao** [comment]
确实，昨天试了IOS 不支持手机浏览器

**Comment by liuzhuoling2011** [comment]
这个正在做，下一版发布会支持移动端


<https://maas.mail.163.com/dashi-web-extend/html/proSignature.html?iconUrl=http%3A%2F%2Fmail-online.nosdn.127.net%2Fb754dcaff541a63038502bc00cbfe6b3.jpg&name=%E5%88%98%E5%8D%93%E7%81%B5&uid=example%40163.com&ftlId=3&items=%5B%22%E9%82%AE%E7%AE%B1%EF%BC%9Aliuzhuoling2011%40hotmail.com%22%5D>
[http://mail-online.nosdn.127.net/b754dcaff541a63038502bc00cbfe6b3.jpg]
刘卓灵
邮箱：liuzhuoling2011@hotmail.com


签名由 网易邮箱大师<https://mail.163.com/dashi/dlpro.html?from=mail88> 定制

在2018年12月08日 10:03，usjinbao<mailto:notifications@github.com> 写道：

确实，昨天试了IOS 不支持手机浏览器
