### ISSUE TITLE
不能登录了

### ISSUE THREAD

**Issue by bestinera** [liuzhuoling2011/baidupcs-web#63]
错误代码: -1, 消息: 网络请求失败, Post https://wappass.baidu.com/wp/api/login: lookup wappass.baidu.com on 8.8.4.4:53: no such host
已登录的账号目录一片空白
现在可以等登了。

**Comment by liuzhuoling2011** [comment]
刚刚试了一下， 貌似正常的

**Comment by bestinera** [comment]
> 刚刚试了一下， 貌似正常的

对的，晚上又试了一次可以登了，之前确实出现了这个问题
