### ISSUE TITLE
LEDE下怎么更新？

### ISSUE THREAD

**Issue by skamoni** [liuzhuoling2011/baidupcs-web#64]
只说将新下载的文件替换掉老版，可是路径在哪？

**Comment by kangyu1230** [comment]
替换 /koolshare/bin/baidupcs  。这问题更适合去koolshare论坛提问。

**Comment by kangyu1230** [comment]
如果LEDE指的是koolshare论坛的OpenWRT/LEDE，替换 /koolshare/bin/baidupcs 即可。

**Comment by skamoni** [comment]
> 如果LEDE指的是koolshare论坛的OpenWRT/LEDE，替换 /koolshare/bin/baidupcs 即可。

谢谢！
