### ISSUE TITLE
请问koolshare LEDE 如何更新

### ISSUE THREAD

**Issue by bluechan** [liuzhuoling2011/baidupcs-web#66]
我复制到到koolshare/bin 目录下，无法启动啊

**Comment by user1121114685** [comment]
/koolshare/bin/baidupcs web --port 5299>/dev/null 2>&1 &

**Comment by Enkannori** [comment]
> 我复制到到koolshare/bin 目录下，无法启动啊

权限设置错误 改成0755即可，不知道怎么设置就重装下 看看原本的设置

**Comment by liuzhuoling2011** [comment]
这个issue和项目本身没有关系， close了
