### ISSUE TITLE
怎么使用web版本 

### ISSUE THREAD

**Issue by usjinbao** [liuzhuoling2011/baidupcs-web#69]
baidupcs-web   JS代码，用什么环境搭建运行 用 IIS  ？apache2?

**Comment by liuzhuoling2011** [comment]
使用go作为http服务器，js代码内嵌在go的执行文件中


<https://maas.mail.163.com/dashi-web-extend/html/proSignature.html?iconUrl=http%3A%2F%2Fmail-online.nosdn.127.net%2Fb754dcaff541a63038502bc00cbfe6b3.jpg&name=%E5%88%98%E5%8D%93%E7%81%B5&uid=example%40163.com&ftlId=3&items=%5B%22%E9%82%AE%E7%AE%B1%EF%BC%9Aliuzhuoling2011%40hotmail.com%22%5D>
[http://mail-online.nosdn.127.net/b754dcaff541a63038502bc00cbfe6b3.jpg]
刘卓灵
邮箱：liuzhuoling2011@hotmail.com


签名由 网易邮箱大师<https://mail.163.com/dashi/dlpro.html?from=mail88> 定制

在2018年12月08日 10:00，usjinbao<mailto:notifications@github.com> 写道：

baidupcs-web JS代码，用什么环境搭建运行 用 IIS ？apache2?
