### ISSUE TITLE
这种下载不了的情况是怎么回事

### ISSUE THREAD

**Issue by usjinbao** [liuzhuoling2011/baidupcs-web#71]
昨天弄好以后下了几个视频测试没问题，今天就下载不了了，从百度登录进去 一切正常，就是使用BaiduPCS-Go就无法下载，所有文件都是无法下载，我换了一个没有使用过BaiduPCS-Go的百度帐号登录BaiduPCS-Go，却都能下载。。这是怎么回事呢

**Comment by usjinbao** [comment]
新帐号下载了2个图片，1个视频后也下载不了了

**Comment by liuzhuoling2011** [comment]
#59 问题重复了，关闭这个issue了
