### ISSUE TITLE
WEB界面下载文件夹多文件时 的显示BUG

### ISSUE THREAD

**Issue by samondlee** [liuzhuoling2011/baidupcs-web#73]
如图，如果在web界面直接选择 某一个文件夹下载

那么 刚在 下载管理 可以看到 正在下载文件夹的文件，但是没有速度，刷新之后，“正在下载 ”没有显示 一个文件

但是实际上后台是在下载的！！！

求解决！！

![default](https://user-images.githubusercontent.com/8521327/49870249-c7a1b280-fe4d-11e8-921c-3bb159f6dae9.JPG)
![1](https://user-images.githubusercontent.com/8521327/49870251-cc666680-fe4d-11e8-9211-f2b4e12ae7a6.JPG)
![3](https://user-images.githubusercontent.com/8521327/49870255-cec8c080-fe4d-11e8-9f0a-9857743dd461.JPG)

补充，程序和浏览器chrome都是最新版的

服务器为armbian

**Comment by liuzhuoling2011** [comment]
目前的下载记录刷新后是会丢失的，这个问题暂时没时间来解决

**Comment by liuzhuoling2011** [comment]
iview在文件夹过多（渲染组件过多）的情况下会卡顿， 正在解决

**Comment by liuzhuoling2011** [comment]
新版本会解决文件过多导致的卡顿问题
