### ISSUE TITLE
下载大文件会卡条，显示 Content-Length is unexpected

### ISSUE THREAD

**Issue by yyc12345** [liuzhuoling2011/baidupcs-web#74]
我今天用这个客户端下较大的文件的时候，前半部分都很顺利，速度也很好。但是到最后的时候就卡条了。我尝试过等待，尝试过暂停下载任务然后继续下载，但是都没有用。打开任务详情里面查看，好几个Task提示Content-Length is unexpected。**想请问下这是个bug么？以及我应该怎么解决？**

OS: Windows 10 x64 Ver 1803
Browser: Chrome 70.0
程序版本: 3.5.9

命令行端没有输出任何多余内容，输出内容与平常下载一致，仅仅是速度为0B/s

资源链接:https://pan.baidu.com/s/1imWD3tQkoHhwedNzKh4aVg 密码:5o8y（希望这个链接对您的复现有帮助）

我的截图：
![snipaste_2018-12-13_10-20-12](https://user-images.githubusercontent.com/13994767/49911568-d7f37500-fec1-11e8-9f0b-9124b28312f6.png)

**Comment by liuzhuoling2011** [comment]
可以试试重启重新下载， 看是不是百度暂时封锁了你的账号

**Comment by yyc12345** [comment]
好吧，好像是封号了。
重新下载也没有数据了，终端提示：user is not authorized, hitcode:123，查了下过往issue #59 ，是封号没错了😭

我当时应该重新下载一下试试的。我还专门开个issue来问...
如果给您带来不便，请谅解。
Close issue.
