### ISSUE TITLE
能否构建一个Docker版？

### ISSUE THREAD

**Issue by ProteinPig** [liuzhuoling2011/baidupcs-web#77]
这样的话对用户会友好一些。
也不用频繁解决环境问题。

**Comment by liuzhuoling2011** [comment]
新手的话， 可以看看这个一键脚本
https://github.com/liuzhuoling2011/baidupcs-web/issues/65

**Comment by ProteinPig** [comment]
我查了一下
auska/docker-baidupcs已经构建了一个Docker版（他个人使用的）。
https://github.com/Auska/docker-baidupcs
