### ISSUE TITLE
解压直接被Win10干掉了~为啥~

### ISSUE THREAD

**Issue by mContext** [liuzhuoling2011/baidupcs-web#79]
![image](https://user-images.githubusercontent.com/9115285/50486540-71c82f80-0a35-11e9-886a-006ff4476d2c.png)

**Comment by liuzhuoling2011** [comment]
这个我之前没有出现过， 可以点击查看详细信息， 然后发出来看看么

**Comment by mContext** [comment]
今天打开没有复现~
