### ISSUE TITLE
设置默认排序

### ISSUE THREAD

**Issue by ayasechan** [liuzhuoling2011/baidupcs-web#81]
希望可以设置文件显示的默认排序

**Comment by ayasechan** [comment]
另外希望能添加在新标签页打开文件夹的功能 这样就不用每次回退到原来的目录 省掉了重新加载页面的时间

**Comment by liuzhuoling2011** [comment]
设置默认排序会在新版本上加上
第二个功能暂时不考虑吧，实现有点困难
