### ISSUE TITLE
发布包和源码有什么区别？

### ISSUE THREAD

**Issue by godhh** [liuzhuoling2011/baidupcs-web#85]
yarn serve 后

App running at:
  - Local:   http://localhost:8081/dist/
  - Network: http://172.16.3.228:8081/dist/

http://127.0.0.1:5299/api/v1/user?method=get 404了
请问下5299是什么服务？

**Comment by liuzhuoling2011** [comment]
发布包已经集成了前端和后台
这个项目的源码包只包含前端代码，默认是调试模式，会找本地的后台服务（可以在release中下载一个后台打开运行， 调试模式下就可以运行了）

**Comment by godhh** [comment]
@liuzhuoling2011 后台的不开源吗？
