### ISSUE TITLE
怎么更改不了appid呢

### ISSUE THREAD

**Issue by lujingyao** [liuzhuoling2011/baidupcs-web#88]
重新设置appid也更改不了，还是默认的id，是怎么回事呢？求帮助

**Comment by liuzhuoling2011** [comment]
你设置的appid是否合法呢？
正常情况下是可以更改的

**Comment by MKChen12** [comment]
我也是这样，按作者说的想改appid为266719，但是一直显示如下
![1547603450 1](https://user-images.githubusercontent.com/26303040/51221438-6ef59600-1974-11e9-8dcd-3a87f49cffb6.jpg)

**Comment by liuzhuoling2011** [comment]
检查一下目录是否存在，或者具有可写权限
![image](https://user-images.githubusercontent.com/8407297/51222900-95b6cb00-197a-11e9-9ae3-cb0f51aa91d2.png)
