### ISSUE TITLE
下载目录修改失败

### ISSUE THREAD

**Issue by cychen95** [liuzhuoling2011/baidupcs-web#90]
不希望放在默认下载目录：root/Downloads/

修改后点击保存显示报错，具体显示如图。

![报错](http://owncloud-c.oss-cn-shanghai.aliyuncs.com/19-1-13/4328551.jpg)

**Comment by loliconer** [comment]
设置的目录不存在就会报这个错

**Comment by cychen95** [comment]
解决！谢谢
