### ISSUE TITLE
请问能自动上传至onedrive吗

### ISSUE THREAD

**Issue by zhangyuchaoren** [liuzhuoling2011/baidupcs-web#92]
配置了一个onedriveupload.sh添加进aria2设置on-download-complete=/root/onedriveupload.sh
使用aria2下载完成之后就可以自动上传至onedrive了   请问这个要在哪里才能添加设置呢

**Comment by user1121114685** [comment]
你能分享下这个onedriveupload.sh项目地址发出来吗？或许我可以尝试下加入到一键脚本里面。

**Comment by kedyao** [comment]
`#!/bin/bash
path=$3 
downloadpath='/usr/local/Download'
filename=''
if [ $2 -eq 0 ]; then
     exit 0
fi

filepath=${path%/*};

if [ "$filepath" = "$downloadpath" ] && [ $2 -eq 1 ]; then #如果下载的是单个文件
      filename=${path// /\\ }                                             
      filename=${filename//[/\\[}                                             
      filename=${filename//]/\\]}                                             
      filename=${filename//&/\\&}
      filename=${filename//@/\\@}
      echo $filename >>/root/name.txt
      eval /usr/local/etc/OneDrive/onedrive -f /Download  $filename >>/root/log.txt
      eval rm -rf $filename
else  #下载的是文件夹
        echo $filepath >>/root/name.txt
        filename_left=${filepath#*Download/}
        echo $filename_left >>/root/name.txt
        filename_right=${filename_left%/*}
        echo $filename_right >>/root/name.txt
        filename=${filename_right// /\\ }
        filename=${filename//[/\\[}
        filename=${filename//]/\\]}
        filename=${filename//&/\\&}
        filename=${filename//@/\\@}
        echo $filename >>/root/name.txt
        #time=$(date "+%Y%m%d-%H%M%S")
        newFilePath=${downloadpath}/${filename}
        #newFilePath=${downloadpath}/${filename}
        echo $newFilePath >>/root/name.txt
        #cd $downloadpath
        #eval mv $filename/ $time/
        eval /usr/local/etc/OneDrive/onedrive-d -f /Download  $newFilePath >>/root/log.txt
        eval rm -rf $newFilePath
fi

exit 0
`

**Comment by user1121114685** [comment]
> 这个是上传的脚本依赖
> https://github.com/0oVicero0/OneDrive
> 这个是上传脚本内容
> #!/bin/bash
> path=$3
> downloadpath='/usr/local/Download'
> filename=''
> if [ $2 -eq 0 ]; then
> exit 0
> fi
> 
> filepath=${path%/*};
> 
> if [ "$filepath" = "$downloadpath" ] && [ $2 -eq 1 ]; then #如果下载的是单个文件
> filename=${path// /\ }
> filename=${filename//[/\[}
> filename=${filename//]/\]}
> filename=${filename//&/\&}
> filename=${filename//@/\@}
> echo $filename >>/root/name.txt
> eval /usr/local/etc/OneDrive/onedrive -f /Download $filename >>/root/log.txt
> eval rm -rf $filename
> else #下载的是文件夹
> echo $filepath >>/root/name.txt
> filename_left=${filepath#_Download/} echo $filename_left >>/root/name.txt filename_right=${filename_left%/_}
> echo $filename_right >>/root/name.txt
> filename=${filename_right// /\ }
> filename=${filename//[/\[}
> filename=${filename//]/\]}
> filename=${filename//&/\&}
> filename=${filename//@/\@}
> echo $filename >>/root/name.txt
> #time=$(date "+%Y%m%d-%H%M%S")
> newFilePath=${downloadpath}/${filename}
> #newFilePath=${downloadpath}/${filename}
> echo $newFilePath >>/root/name.txt
> #cd $downloadpath
> #eval mv $filename/ $time/
> eval /usr/local/etc/OneDrive/onedrive-d -f /Download $newFilePath >>/root/log.txt
> eval rm -rf $newFilePath
> fi
> 
> exit 0

我看这个是自成一体的，应该不需要集成到脚本中。非常感谢您的提供
