### ISSUE TITLE
任务已经终结

### ISSUE THREAD

**Issue by cxl676** [liuzhuoling2011/baidupcs-web#95]
点击任务下载，然后到上传下载管理中查看，发现未开始下载。点击暂停按钮或者任务详情按钮提示任务已经终结

**Comment by liuzhuoling2011** [comment]
可以把后台的输出截图看看

**Comment by cxl676** [comment]
> 可以把后台的输出截图看看

这个是web版的，怎么看后台输出

**Comment by XinXinkkk** [comment]
> 
> 
> > 可以把后台的输出截图看看
> 
> 这个是web版的，怎么看后台输出 linux arm64版本

不是还有dos窗口嘛，就那个

**Comment by kkh66** [comment]
有吗

**Comment by sam0773** [comment]
同问题。在群晖里面装的下载提示任务已经终结，下载windows版本测试也相同。。

**Comment by hebuda** [comment]
遇见了同样的问题
