### ISSUE TITLE
是不是不能用了？

### ISSUE THREAD

**Issue by tenhow** [liuzhuoling2011/baidupcs-web#96]
前两天还是满速下载，今天没有速度了

**Comment by liuzhuoling2011** [comment]
目前百度是针对账号进行限速，当一个非会员账号下载量达到一定阈值就会触发限速。账号被限速之后容易出现下载错误、掉连接数等问题，需要过几天或者开通会员才会恢复"
代码: 31326, 消息: user is not authorized, hitcode:123

**Comment by tenhow** [comment]
好快！
实际上我是开了会员，前个月被限速就开了，那如果说你能用的话那可能是我这边的网络问题吧。

**Comment by loliconer** [comment]
开了普通会员也会被限速，估计只有SVIP才没有限制

**Comment by tenhow** [comment]
真的是，果然是被这个限速了。
我找其他第三方试了，结果一样。
拿应该是这个原因。

**Comment by tenhow** [comment]
我又用PanDownload测试了，确定没有限速。
然后我将Baidupcs-Web在debian和mac上（同一局域网内）跑了一次，都不能下载。
等下测试换个网看看
