### ISSUE TITLE
小白问下更新问题

### ISSUE THREAD

**Issue by leslie3747** [liuzhuoling2011/baidupcs-web#98]
我是软路由LEDE里的软件中心下载的，更新时说是替换版本，但不知道安装路径在哪里
软件中心里安装的3.5.7版本，没有办法修改下载路径，提示输入的文件夹路径错误，另外如何修改为局域网内nas上的目录。

**Comment by liuzhuoling2011** [comment]
这个情况我就不清楚了， 看能不能重新上传新版到软路由LEDE里的软件中心
