### ISSUE TITLE
为什么我下载的下来的压缩文件里没有exe...

### ISSUE THREAD

**Issue by 653322185** [liuzhuoling2011/baidupcs-web#99]
为什么我下载的下来的压缩文件里没有exe...是我哪里操作失误了吗？我下载的是baidupcs-web-3.6.3.zip

**Comment by liuzhuoling2011** [comment]
http://qiniu.zoranjojo.top/BaiduPCS-Go-3.6.3-windows-86.zip
http://qiniu.zoranjojo.top/BaiduPCS-Go-3.6.3-windows-amd64.zip
